Migrate to androidx and add NumberPickerPreference
Coppernic/AndroidUtils pull request #4
Opened 2020-04-01 15:22 UTC by mreynier

2020-04-01 16:40 UTC, bastienpaulfr requested changes

2020-04-01 16:40 UTC, bastienpaulfr commented on core/build.gradle
> +    implementation 'androidx.preference:preference:1.1.0'
Je serais plus partisan de créer un module `ui`  pour mettre les composants graphiques, dont les préférences. Qu'en penses-tu ?

2020-04-02 14:52 UTC, bastienpaulfr requested changes

2020-04-02 14:52 UTC, bastienpaulfr commented on ui/build.gradle
> +    buildToolsVersion "29.0.2"
Pas besoin des build tool ici

2020-04-02 14:52 UTC, bastienpaulfr commented on ui/build.gradle
> +        versionName "1.0"
Aille aille aille, il faut utiliser le plugin de versioning pour récupérer le numéro de version

2020-04-02 14:52 UTC, bastienpaulfr commented on ui/build.gradle
> +    implementation 'fr.bipi.treessence:treessence:0.3.0'
A mettre en test et androidTest implementation. Mais surtout pas en implementation.

2020-04-02 15:12 UTC, mreynier commented on ui/build.gradle
> +    implementation 'fr.bipi.treessence:treessence:0.3.0'
tu parle slf4j ou bipi?
SI j'enleve bipi, timber ne marche plus. Tu veux que j'ajoute la lib timber direct?

2020-04-02 16:49 UTC, bastienpaulfr commented on ui/build.gradle
> +    implementation 'fr.bipi.treessence:treessence:0.3.0'
Dans les libs on ne mets que slf4J
Timber c'est pour les applis. 
Après, je ne me souviens plus si j'ai migré AndroidUtils vers SLF4J. Ca peut être l'objet d'un futur ticket

2020-04-02 16:52 UTC, bastienpaulfr approved these changes

2020-04-02 16:52 UTC, bastienpaulfr commented on ui/build.gradle
> +    implementation 'com.jakewharton.timber:timber:4.7.1'
Prévoir de passer la lib à SLF4J dans le futur (Sur le modèle de la lib Interactor)

2020-04-06 09:47 UTC, merged